### PR TITLE
Bug/#68/accel cls args

### PR DESCRIPTION
**Pull request by JoschD**
Solves Issue #68

### CODE REVIEW

**Comment by JoschD** [comment]
@jaimecp89 @elenafol creator.py needs now "--type" infront of "nominal" (or "best_knowledge" or whatever). That's one of the things, that would add more ifs and checks into entrypoint and I don't see a reason, why certain parameters shouldn't have flags in our usual usage. Open for discussion, though.

**Comment by awegsche** [comment]
can we merge this pull request? i need it in order to go on.

**Comment by jaimecp89** [comment]
@elenafol Is the --type thing in the model creator in the GUI already?
Otherwise it will break...

**Comment by awegsche** [comment]
Or can I merge it somehow into my branch (or is this bad manners?)?

**Comment by jaimecp89** [comment]
Yeah feel free, we should probably just control what goes into master.

**Comment by elenafol** [comment]
--type added to the model creation arguments in the GUI. Is not released yet, I am still testing.

**Comment by elenafol** [comment]
GUI released. You can merge

**Pull request merged**
